### ISSUE TITLE
Vagrant builder timeouts waiting for SSH

### ISSUE THREAD

**Issue by kesonno** [themalkolm/packer-builder-vagrant#1]
Hello @themalkolm, 

I've tried with several vagrant boxes and the result appear to be always the same: `packer build` command always hang with the message "vagrant: Waiting for SSH to become available...", then reach its timeout and abort the process.

My system:
* Host OS X Yosemite 10.10.5
* Vagrant 1.8.5
* VirtualBox 5.0.26
* Packer 0.11.0
* packer-builder-vagrant v0.0.7 ( packer-0.11.0_packer-builder-vagrant_darwin_amd64 )

This is the template I'm using:

```json
{
  "builders": [{
    "type": "vagrant",

    "box_name": "bento/centos-7.2",
    "box_provider": "virtualbox",
    "box_file": ".ovf",

    "builder": {
      "type": "virtualbox-ovf",
      "guest_additions_mode": "disable",
      "headless": false,
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_pty": true,
      "ssh_timeout": "10m",
      "shutdown_command": "echo '/sbin/halt -h -p' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'"
    }
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "sleep 30",
      "sudo apt-get update",
      "sudo apt-get install -y php7.0 libapache2-mod-php7.0 php7.0 php-xdebug php7.0-common php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-curl php7.0-intl php7.0-xsl php7.0-mbstring php7.0-zip php7.0-bcmath php7.0-iconv"
    ]
  }]
}
```
I've tried with following boxes:
* ubuntu/xenial64
* boxcutter/ubuntu1604
* bento/centos-7.2

Same boxes, launched with `vagrant init <box name>; vagrant up --provider virtualbox`, works fine on my system.

To try to debug, I'm running with `headless: false`, but the result vary box by box: with the ubuntu/xenial64, the boot of the vm hang with the message "random: nonblocking pool is initialized", with boxcutter/ubuntu1604 the boot hang with another error (sorry I have not take note of it), while with bento/centos-7.2 the system boot correctly, and I can login at the prompt with vagrant/vagrant. But in all cases packer abort the build because Vagrant can't connect with the vm.

Let me know if I can provide additional details.

Thanks
Gennaro

**Comment by kesonno** [comment]
Just a note: I'm running packer 0.11.0 because the packer-builder-vagrant v0.0.7 report "0.11.0" in the name of the released file, and the README state that I need to match packer version exactly.

**Comment by themalkolm** [comment]
@kesonno have you tried running the test script we have? It performs the whole cycle with eventual check that the new box is responsive:

```
$ cd test/virtualbox
$ ./test.sh
...
```

Here are my specs for comparison:

* Host OS X El Capitan 10.11.6
* Vagrant 1.9.1
* VirtualBox 5.1.12 r112440
* Packer 0.11.0
* packer-builder-vagrant v0.0.7 ( packer-0.11.0_packer-builder-vagrant_darwin_amd64 )

It works for me.

**Comment by themalkolm** [comment]
Btw, this plugin does very little. Does packer work OK if you don't use it but instead use `virtualbox-ovf` directly and explicitly provide value for `source_path`?

**Comment by themalkolm** [comment]
Say, something like this (you need to manually add this vagrant box first of course with vagrant box add etc.):

```
{
  "builders": [{
      "type": "virtualbox-ovf",
      "source_path": "/Users/johndoe/.vagrant.d/boxes/bento-VAGRANTSLASH-centos-7.2/2.3.1/virtualbox/box.ovf"
      "guest_additions_mode": "disable",
      "headless": false,
      "ssh_username": "vagrant",
      "ssh_password": "vagrant",
      "ssh_pty": true,
      "ssh_timeout": "10m",
      "shutdown_command": "echo '/sbin/halt -h -p' > /tmp/shutdown.sh; echo 'vagrant'|sudo -S sh '/tmp/shutdown.sh'"
  }],
  "provisioners": [{
    "type": "shell",
    "inline": [
      "sleep 30",
      "sudo apt-get update",
      "sudo apt-get install -y php7.0 libapache2-mod-php7.0 php7.0 php-xdebug php7.0-common php7.0-gd php7.0-mysql php7.0-mcrypt php7.0-curl php7.0-intl php7.0-xsl php7.0-mbstring php7.0-zip php7.0-bcmath php7.0-iconv"
    ]
  }]
}
```

**Comment by kesonno** [comment]
Hello @themalkolm, thanks for you replies.

Same result with test.sh script, but you are right, the problem isn't in the plugin: same result (packer timeouts waiting for SSH), even using directly virtualbox-ovf builder.

I'll try to upgrade Vagrant and Virtualbox to try to match your environment, I hope I don't need to upgrade even the OS :(

Anyway, thanks for your support, I guess I can close the issue.

**Comment by themalkolm** [comment]
Pretty sure the problem is with VirtualBox.

**Comment by themalkolm** [comment]
:) If by any chance you manage only to make it work for packer 0.12 - ping me and we will try to compile a binary for you
