### ISSUE TITLE
More than one provider

### ISSUE THREAD

**Issue by shurick81** [themalkolm/packer-builder-vagrant#12]
Is there any possibility to use this builder with multiple providers? Let's say with Virtualbox, VMware and Hyper-V?

**Comment by themalkolm** [comment]
Sorry, Virtualbox only. Any pull requests are welcome adding such support.

**Comment by grv87** [comment]
@themalkolm, could you tell what exactly should be changed/implemented (except tests) to add another provider? I don't see any code tied to VirtualBox. Or this issue was resolved, and now all Vagrant providers are supported?

**Comment by themalkolm** [comment]
I'm simply don't have time to add support for other providers. Maybe it is trivial to extend it to other providers. Maybe not. You tell me. 🤷‍♂️
