### ISSUE TITLE
Can't build versioned boxes (v2018.04.15)

### ISSUE THREAD

**Issue by avishnyakov** [themalkolm/packer-builder-vagrant#14]
Reminds #11, can't figure out how to build versioned boxes. I might miss something, but been building with this plugin for more than a year - all custom built boxes without versions. 

The plugin itself super-rocks, drastically reduces time to build boxes under CI/CD!

Say, vagrant box list
```
alpine/alpine64                           (virtualbox, 3.7.0)
generic/alpine37                          (virtualbox, 1.8.12)
generic/alpine37                          (virtualbox, 1.8.38)
```

Under ~/.vagrant.d/boxes/
```
tree alpine-VAGRANTSLASH-alpine64/
alpine-VAGRANTSLASH-alpine64/
├── 3.7.0
│   └── virtualbox
│       ├── Vagrantfile
│       ├── box-disk001.vmdk
│       ├── box.ovf
│       └── metadata.json
└── metadata_url
```

Packer config, with or without box_version=3.7.0
```
"builders": [
      {
        "type": "vagrant",
        "box_provider": "virtualbox",
        "box_file": ".ovf",
        "box_name": "alpine/alpine64",
        "box_version": "3.7.0",
        "builder": {
          "type": "virtualbox-ovf",
          "headless": "true",
          "boot_wait": "30s",
          "ssh_username": "vagrant",
          "ssh_password": "vagrant",
          "ssh_wait_timeout": "8h",
          "shutdown_command": "sudo -S sh -c '/usr/sbin/shutdown -h'",
          "shutdown_timeout": "15m",

          "output_directory": "{{user `output_directory`}}",
          "http_directory": "{{user `http_directory`}}"
        }
      }
    ],
```

Output:
```
vagrant output will be in this color.
vagrant: (vagrant) Builder source_path ...
Build 'vagrant' errored: open : no such file or directory
==> Some builds didn't complete successfully and had errors:
vagrant: open : no such file or directory
```

It might be useful to output a bit more details, such as box path here:
https://github.com/themalkolm/packer-builder-vagrant/blob/8a4a5a247defd805eaa7c6540ecce5f94db768e6/step_fetch_box.go#L37

Anything I can help with here?

**Comment by avishnyakov** [comment]
Ha, interesting. Can pass suggested regression on troubleshooting guide. 
Looks like plugin is ok and problems somewhere on my side.

```
$ git clone https://github.com/themalkolm/packer-builder-vagrant.git
$ cd packer-builder-vagrant
$ cd test/virtualbox
$ ./test.sh
...
OK
``

**Comment by themalkolm** [comment]
:)

**Comment by avishnyakov** [comment]
@themalkolm shhh :) 

So at the end I see that plugin works as expected, however:
* [OK] - running bare sh script cmd
* [FAIL] - running same same sh cmd under puppet exec resource

I bet that puppet messes up with PATH or something, therefore a bunch of variables aren't set or propagated to packer/vagrant later on.

Got plugins sources, built locally and trying to figure out what is happening.

**Comment by themalkolm** [comment]
Yep, it is sensitive to PATH:

* Uses it to find the plugin itself (kind of)
* Uses it to find Vagrantfile
* Uses it to find cached vagrant boxes etc.
* Uses it to store artifacts
* ...

I agree that some extra logging is required to debug issues like this one. Do you need help with finding where exactly it fails? It should be easy, just drop printfs in every error check condition :)

**Comment by themalkolm** [comment]
Oh yeah, vagrant/packer themselves are sensitive to HOME as well.

**Comment by avishnyakov** [comment]
Thanks for suggestions. Adding more logging, will share findings once puppet based runs work.
It's just that we can do with scripting but puppet is much more preferable way, hence keen to fix it up.

**Comment by dragon788** [comment]
Typically configuration management tools run as root which does not source a lot of the environment files that setup the path.  Have you tried telling it to run the build as a different user?

**Comment by themalkolm** [comment]
They also allow to run commands as other users with modified env if required, right? Why would you run packer as root?

**Comment by avishnyakov** [comment]
Hey guys, back on this.

Agree with @themalkolm, Dockerfile for build and a bit more trace will make it better.
HOME and some other env variables most likely is the key here.

I can do successful packer build as simple as this (just an example)
```
cd ~/packer_builds && env | sort \
    && packer build \
        -var http_directory=~/packer_bin \
        -var output_directory=~/packer_output \
        -var vagrant_box_output=centos7-atomic-host.box \
        -force -debug 
    centos7-atomic-host.json
```

Now we put the same cmd under puppet exec resource - that's where we fail.

```
$packer_build_cmd = "...same-same cmd..."

exec { "packer build - ${packer_file_name}" :
  command   => $packer_build_cmd,
  logoutput => true,
  # 12 hours
  timeout   => 60 * 60 * 12
}
```

Now the puppet story.
- puppet 5.5.6 
- only in a local mode - puppet apply, local manifest (so we control the use who runs it)
- stupidly simple - exec resources to wrap and chain packer -> vagrant box add execution
- use puppet as an "abstraction" for other things, including vagrant/packer on win/masoc 

Didn't expect but seems that puppet unsets HOME and a few other variables. 
> https://projects.puppetlabs.com/issues/5224

Tracing execution, env variables are different from shell exec and puppet one.
* HOME is missed under puppet, and further vagrant exec (thanks @themalkolm  for the hint)
* vagrant box add creates a local ".vagrant.d" folder within current folder - looks like it indeed missed the home and therefore hits the current dir creating a new .vagrant.d

Let me get more data on this, going to play with puppet exec environment attribute.

**Comment by avishnyakov** [comment]
Bang!

HOME and USER are required to get packer/vagrant up, at least under macos


```
exec { "packer build - ${packer_file_name}" :
  command     => $packer_build_cmd,
  logoutput   => true,
  # 12 hours
  timeout     => 60 * 60 * 12,
  environment => [
    "HOME=$home",
    "USER=$user"
  ]
}
```

Propagating with facter, works.
```
FACTER_path=$PATH \
FACTER_USER=$USER \
FACTER_HOME=$HOME \
FACTER_mb_packer_file=centos7-atomic-host.json \
FACTER_mb_vagrant_box_name=centos7-atomic-host \
puppet apply ....
```

Same with vagrant box add, something like this
```
exec {"vagrant box add - ${packer_file_name}" : 
  command   => join([
    "vagrant box add",
    "${vagrant_box_path}",
    "--name $vagrant_box",
    "--force"
  ], " "),
  # 15 minutes
  timeout   => 60 * 15,
  logoutput => true,
  environment => [
    "HOME=$home",
    "USER=$user"
  ]
}
```

I think we can close this one. It all looks super-cool.

**Comment by avishnyakov** [comment]
Same on windows - packer/vagrant need home and username variables. 
Propagating via facter down to puppet exec environment - all works like a charm, now on mac and windows. 

```
SET "FACTER_HOME=%HOME%" `
&& SET "FACTER_USER=%USERNAME%" `
&& SET "FACTER_PATH=%PATH%" `
puppet apply ....
```

**Comment by themalkolm** [comment]
So setting user works - nice, it is probably the easiest workaround and things are working. Yaw! Have you checked these env variables?

* https://www.packer.io/docs/other/environment-variables.html
* https://www.vagrantup.com/docs/other/environmental-variables.html

VAGRANT_HOME looks very promising, I think this is what hits you with vagrant. Does _packer_ actually require HOME & USER?

**Comment by themalkolm** [comment]
Didn't know that puppet unsets HOME, this is interesting.

**Comment by avishnyakov** [comment]
Good question. I think I am a bit wrong, here is what happens:

1) default installation of packer/vagrant make use default user settings, trying to resolve ~/.vagrant or something like this
2) puppet unsets HOME/USER, therefore it "looks" like these vars are needed
3) essentially, repointing VAGRANT_HOME and PACKER_CACHE_DIR is a good idea 

A few pros/cons around this:
* custom VAGRANT_HOME won't work with default vagrant installs - good for separation but box/plugins installs is needed again
* custom VAGRANT_HOME makes it easier to offload storage and avoid bloated system drives
* CI based setup which runs under custom user might have it's own, fully isolated vagrant instance

Hope that now makes more sense. Going to give it a try.

**Comment by avishnyakov** [comment]
Confirming that VAGRANT_HOME solve all problems. It's not about HOME/USER, it's all about correct VAGRANT_HOME value.

Thanks guys!

**Comment by themalkolm** [comment]
Do you mind to make a pull request to README explaining the problem & workaround? :)
