### ISSUE TITLE
Is it possible to support linked_clone option?

### ISSUE THREAD

**Issue by avishnyakov** [themalkolm/packer-builder-vagrant#15]
Hey @themalkolm, is it feasible to add linked_clone support for this awesome builder?

Vagrant supports VirtualBox Linked Clones feature as following. It cuts minutes to seconds to boot up a new VM:
> https://www.vagrantup.com/docs/virtualbox/configuration.html#linked-clones

I wonder if it even possible for this builder. Is so, we'll bypass "Importing VMxxx-yyy-zzz/0/virtualbox/box.ovf" stage which takes ages for windows boxes.

What do you think?

**Comment by themalkolm** [comment]
This builder simply pre-downloads vagrant boxes and then passes control to the packer process. We simply help to resolve vagrant box name to a source_path with .ovf file. The rest is done by the packer itself.

The feature you mentioned makes sense but support for it should be added somewhere else. It could be virtualbox-ovf builder itself or most likely a new builder completely. I found this issue with some ideas and thoughts https://github.com/hashicorp/packer/issues/6516.

Another thing you could try is to switch to vmware-vmx. Looks like packer already supports clone feature there out of the box https://www.packer.io/docs/builders/vmware-vmx.html#linked.

What do you think?

**Comment by avishnyakov** [comment]
Sorry for the late reply. Agree, makes sense.

That said, linked_clone management is a pain. Could be too hard to make a decision on should we leave or delete the linked_clone VM. Importing new box with override, for example, etc.
