### ISSUE TITLE
`-force` flag does not work

### ISSUE THREAD

**Issue by kadimi** [themalkolm/packer-builder-vagrant#2]
Hi @themalkolm,

It would be great if you could implement the [`-force` flag](https://www.packer.io/docs/command-line/build.html#_force).

Thanks
Nabil

**Comment by themalkolm** [comment]
@kadimi could you elaborate a little? What do you expect to happen when `-force` flag is provided?

Lets define what it should do together and I will implement it if it helps you. Deal?

> -force - Forces a builder to run when artifacts from a previous build prevent a build from running. The exact behavior of a forced build is left to the builder. In general, a builder supporting the forced build will remove the artifacts from the previous build. This will allow the user to repeat a build without having to manually clean these artifacts beforehand.

**Comment by kadimi** [comment]
Thanks for your response @themalkolm, my build look like this: 

```sh
rm ./output- -fr && packer build template.json
```

I was hoping I could do like suggested by the error message :

```sh
packer build -force template.json 
```

---

Here is a failed build output:
```

vagrant output will be in this color.

    vagrant: (vagrant) Builder source_path ...
    vagrant: (vagrant) Builder source_path: /home/n/.vagrant.d/boxes/debian-VAGRANTSLASH-jessie64/8.7.0/virtualbox/box.ovf
    vagrant: (vagrant) Builder type ...
    vagrant: (vagrant) Builder type: virtualbox-ovf
    vagrant: (vagrant) Builder ...
    vagrant: (vagrant) Builder: OK
    vagrant: (vagrant) Builder prepare ...
    vagrant: (vagrant) Builder prepare: OK
    vagrant: (vagrant) Builder run ...
==> vagrant: Output directory exists: output-
==> vagrant: 
==> vagrant: Use the force flag to delete it prior to building.
Build 'vagrant' errored: Output directory exists: output-

Use the force flag to delete it prior to building.

==> Some builds didn't complete successfully and had errors:
--> vagrant: Output directory exists: output-

Use the force flag to delete it prior to building.

==> Builds finished but no artifacts were created.

```

**Comment by themalkolm** [comment]
@kadimi sure, will do. I will make a patch release for packer-0.12.2. Does it work for you?

**Comment by kadimi** [comment]
@themalkolm That would be awesome!

**Comment by themalkolm** [comment]
@kadimi https://github.com/themalkolm/packer-builder-vagrant/releases/tag/v0.1.3

Now `-force` (and `-debug`) are passed down to the wrapped builder. So your use case now should work.

**Comment by kadimi** [comment]
> So your use case now should work.

It surely does, thanks @themalkolm.
