### ISSUE TITLE
packer-0.12.0_packer-builder-vagrant_linux_amd64 - where is it?

### ISSUE THREAD

**Issue by devopsman** [themalkolm/packer-builder-vagrant#4]
That plugin is missing. As I understand it requires building. Any doc on how to get it would be nice

**Comment by themalkolm** [comment]
@devopsman do you mean you want a plugin for 0.12.0 instead of 0.12.2?

**Comment by devopsman** [comment]
@themalkolm I'm using packer 0.12.2, but my question was where to get that plugin? Or should I compile it myself? If so could you please provide some steps to do that as I didn't work with go code..

I'm not able to locate  "packer-0.12.0_packer-builder-vagrant_linux_amd64" as said in that step:
$ cp packer-0.12.0_packer-builder-vagrant_linux_amd64 ~/.packer.d/plugins/packer-builder-vagrant

**Comment by themalkolm** [comment]
@devopsman Sorry, must be forgot to mention that. You can download compiled binaries from here https://github.com/themalkolm/packer-builder-vagrant/releases

**Comment by devopsman** [comment]
Thanks, that's what I was looking for!

**Comment by themalkolm** [comment]
@devopsman Happy to help! I update README.md with the link. Thanks!
