### ISSUE TITLE
VMware fusion vagrant box example

### ISSUE THREAD

**Issue by matti** [themalkolm/packer-builder-vagrant#6]
Could docs (readme) have an example of this?

**Comment by themalkolm** [comment]
@matti have you tried to guess how it should work with vmware? Do you have a working vmware setup you want to automate with this plugin?

**Comment by matti** [comment]
No. I'm too lazy to invest time in this and then figure out that it just doesn't work :)

**Comment by matti** [comment]
(and yes, I have a project where I would like to publish vmware boxes to vagrant automatically)

**Comment by themalkolm** [comment]
Well, I don't want to commit into something you are not willing to commit. Draw.

**Comment by matti** [comment]
:beer: deserved

**Comment by themalkolm** [comment]
:) Poke if you change your mind. We can do it together :)

**Comment by dragon788** [comment]
Is this plugin generic enough it would work with VMware and just needs documented or it needs some handling to output the right kind of box for the normal post processors to handle?

**Comment by themalkolm** [comment]
Well, we need somebody to figure out what to do and I can automate it here.

I don't know how much you need to do in case of VMware. This plugin is veeeery simple.
