### ISSUE TITLE
Packer 1.0.0 support

### ISSUE THREAD

**Issue by znerd** [themalkolm/packer-builder-vagrant#7]
Please support Packer 1.0.0, released on April 4, 2017. See:
https://github.com/hashicorp/packer/blob/master/CHANGELOG.md

**Comment by themalkolm** [comment]
Do you use this plugin?

**Comment by znerd** [comment]
Not yet, but I would like to.

I'm using Packer 1.0.0 with Vagrant and VMware, and I'd like to automatically download the (Vagrant and VMware) Vagrant boxes (Bento CentOS 7.3), provision them with Packer, and then upload them to Atlas.

**Comment by znerd** [comment]
I downgraded to Packer 0.12.2 so I would be able to use your plugin, but now I'm hit by issue #5.

**Comment by themalkolm** [comment]
Migrated to packer `v1.0.0`

https://github.com/themalkolm/packer-builder-vagrant/releases/tag/v2017.05.10
