### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by srggavrilov** [themalkolm/packer-builder-vagrant#9]
Since the plugin is hardly coupled with the Packer version, it would be great, if someone provides instructions on how to build it from source against specific Packer version. Or even better - to configure automatic builds on  CI.

Is there any plans on that?

**Comment by themalkolm** [comment]
[README.md](https://github.com/themalkolm/packer-builder-vagrant/blob/master/README.md) has a badge with build status. It looks like this (btw, you can click on it): [![Build Status](https://travis-ci.org/themalkolm/packer-builder-vagrant.svg?branch=master)](https://travis-ci.org/themalkolm/packer-builder-vagrant)

It is being build in travis:
- https://github.com/themalkolm/packer-builder-vagrant/blob/master/.travis.yml
- https://travis-ci.org/themalkolm/packer-builder-vagrant

Building against different packer version is a non-trivial task. You need to update packer dependency in the code and make sure everything still works. What packer version do you use?

**Comment by srggavrilov** [comment]
I'm on 1.0.0, while 1.0.2 has already been released. Not a big deal for now. But I'm going to redesign our build process using `packer-builder-vagrant` and feel a little concern about what will be when I have to upgrade packer and could I solve it by myself.

**Comment by themalkolm** [comment]
I can help with I updates. Minor bumps are simple.

Btw, have you checked another hack I have to create vagrant boxes in post-processor? :) README is not up to date there but you should get the idea. This makes it possible to have a pipeline of locally built vagrant boxes from a scratch one (freshly install OS yourself) to the final ones.

https://github.com/themalkolm/packer-post-processor-vagrant-upload

**Comment by themalkolm** [comment]
Here, updated to 1.0.2: https://github.com/themalkolm/packer-builder-vagrant/releases/tag/v2017.07.14

To bump packer version now you simply change `PACKER_VERSION` variable in [Makefile](https://github.com/themalkolm/packer-builder-vagrant/blob/master/Makefile#L6)

**Comment by srggavrilov** [comment]
Great! Thank you. I'll check it (both: postprocessor and build instructions) and let you know of the results. It's sad that this code is not at mainline of Packer. Have you tried to PR it?

**Comment by themalkolm** [comment]
Meh, I'm happy with the way it is.

**Comment by srggavrilov** [comment]
After a quick look at `packer-post-processor-vagrant-upload` I don't have an idea how it'd help to build vagrant boxes from scratch as you mentioned above. It makes it possible to upload vagrant boxes to S3, doesn't it?

**Comment by themalkolm** [comment]
The origin has S3 but I added (`file:///some/local/path`) support for local repos i.e. so you can do

```
scratch -> packer -> vagrant repo -> packer -> vagrant repo -> packer -> ...
```

`packer-builder-vagrant` takes vagrant box and produces another `*.box` file, right? The idea behind `packer-post-processor-vagrant-upload` is to close the loop and allow packer to write to the local repo itself.

**Comment by themalkolm** [comment]
The build was greatly simplified and more or less it is done by simply bumping PACKER_VERSION in makefile. It is very simple.
